---
booktitle: Proceedings of the Workshop on New Challenges for Feature Selection in
  Data Mining and Knowledge Discovery at ECML/PKDD 2008
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
volume: 4
year: '2008'
shortname: FSDM
start: 2008-09-15
end: 2008-09-15
published: 2008-09-11
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
bibsource: http://jmlr.csail.mit.edu/proceedings/
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
id: SaeysYLHIIWLPd2008
month: 0
cycles: false
editor:
- given: Yvan
  family: Saeys
- given: Huan
  family: Liu
- given: Iñaki
  family: Inza
- given: Louis
  family: Wehenkel
- given: Yves Van de
  family: Pee
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Workshop on New Challenges for Feature Selection in Data  Mining and Knowledge Discovery at ECML/PKDD 2008
    Held in Antwerp, Belgium on 15 September 2008

  Published as Volume 4 by the Proceedings of Machine Learning Research on 11 September 2008.

  Volume Edited by:
    Yvan Saeys
    Huan Liu
    Iñaki Inza
    Louis Wehenkel
    Yves Van de Pee

  Series Editors:
    Neil D. Lawrence
date_str: 15 Sep
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v4"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v4
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: New Challenges for Feature Selection in Data Mining and Knowledge Discovery
  url: http://bioinformatics.psb.ugent.be/fsdm2008
  location: Antwerp, Belgium
  dates:
  - 2008-09-15
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
